aws_region           = "us-east-1"
environment          = "dev"
project_name         = "terraform-project"
vpc_cidr             = "10.0.0.0/16"
availability_zones   = ["us-east-1a", "us-east-1b"]
public_subnet_cidrs  = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidrs = ["10.0.11.0/24", "10.0.12.0/24"]
instance_type        = "t3.micro"
db_instance_type     = "db.t3.micro"
db_username          = "dbadmin"
db_password          = "CHANGE_ME"   # set via TF_VAR_db_password env var or AWS Secrets Manager
